### ISSUE TITLE
Contract-level metadata how can I set banner image url?

### ISSUE THREAD

**Issue by akantora** [ProjectOpenSea/opensea-creatures#124]
The problem is the owner of that contract is a factory contract instead of me so I need to set it up via metadata.
what is key to set banner image URL and collection profile in contract-level metadata? 
also, can we update collection contract metadata after deployment?

really need some help here tried googling and random key but still can't fix the problem.

**Comment by chahakshah111** [comment]
you can check here: https://docs.opensea.io/docs/contract-level-metadata.
and yes you can update contract-level metadata by just pointing to another URI.

**Comment by akantora** [comment]
> you can check here: https://docs.opensea.io/docs/contract-level-metadata.
> and yes you can update contract-level metadata by just pointing to another URI.
> and not sure about the banner image_url as it seems to be not working.

https://docs.opensea.io/docs/contract-level-metadata 
I saw this one but didn't help at all still don't know the key to set Banner, profile, Twitter URL, and Discord URL

**Comment by akantora** [comment]
I got a solution to this issue not actually fix it but just don't need to set it via contract-level metadata anymore.
hope there will be more cleary example on this issue in future.
