### ISSUE TITLE
Unhandled promise rejection while trying to run the mint script on mainnet.

### ISSUE THREAD

**Issue by clonetwin26** [ProjectOpenSea/opensea-creatures#138]
Hi all everything deployed just fine on rinkeby and only had issues deploying to mainnet. 

I was able to create this contract https://etherscan.io/address/0x457d45ab5da3766c4dc5b7fe6e3cdeeac969fb79.

But when I run the mint script I get errors:

(node:17256) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "transactionHash": "0x4887351a61de6caf5ec6014ff453b24324b812ba5335c7679184504135253738",
  "blockHash": "0x6acda387282752181789607ba55ea3c0a2ed35ccc16d2cbf215aff601a4f3e01",
  "blockNumber": 13316444,
  "contractAddress": null,
  "cumulativeGasUsed": 991782,
  "effectiveGasPrice": "0x286a8b62af",
  "from": "0x309fd00a5f19e217b08e832654a2e4169247fe92",
  "gasUsed": 21602,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xd8a790aed148238898369233ebcc9f7c56b719e7",
  "transactionIndex": 10,
  "type": "0x0",
  "events": {}
}
    at Object.TransactionError (/Users/ryanmac/work/mcr_nfts/node_modules/web3-eth/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/Users/ryanmac/work/mcr_nfts/node_modules/web3-eth/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /Users/ryanmac/work/mcr_nfts/node_modules/web3-eth/node_modules/web3-core-method/lib/index.js:394:57
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)

Any advice on how to get to a better error message or what exactly I am doing wrong would be so helpful. I am on the finish line here and stuck on this thing :/

**Comment by itinance** [comment]
Are you sure to call this method from the Owner? 

`mintTo` has the "**onlyOwner**"-Modified. This way you have to call the function from `{from: yourOwnerWallet}` which is basically the account you have used for contract deployment

**Comment by clonetwin26** [comment]
So the issue here was incorrectly deploying the contract in the first place. The default settings in truffle.yaml didn't quite work. You have to make sure both the initial contract and creature finishes all the way and then the minting will work as expected

**Comment by clonetwin26** [comment]
Please update truff

**Comment by itinance** [comment]
Wanna submit a PR?

**Comment by clonetwin26** [comment]
I gave a PR a go but it won't let me submit my branch.

Its a simple change to truffle.js explaining that a gas price of 5 gwei is much to low and will cause all kinds of side effects when deploying to mainnet.

         return new HDWalletProvider(MNEMONIC, mainnetNodeUrl);
       },
       gas: 5000000,
-      gasPrice: 5000000000,
+      gasPrice: 5000000000, // Set this to a realistic gas price on the day you deploy to main.
     },
   },

**Comment by itinance** [comment]
I'm curious that you even could compile everything. I got in stuck with truffle: https://github.com/ProjectOpenSea/opensea-creatures/issues/139
