### ISSUE TITLE
Nothing happens after compilation

### ISSUE THREAD

**Issue by tabz11** [ProjectOpenSea/opensea-creatures#14]
Hi,
I have done some modifications to the original contract(variable names only). When I try to deploy it gives me error:
`compiling your contracts`  
`Everything up to date, there is nothing to compile`

nothing happens?

Please help!

**Comment by iraniamir** [comment]
@tabz11 any solution?

**Comment by alexanderatallah** [comment]
You probably did it once before. You need to do `truffle migrate --reset`
