### ISSUE TITLE
ERC1155Tradeable.sol: what actually is the real difference between "create" and "mint"-functions?

### ISSUE THREAD

**Issue by MrsBookik** [ProjectOpenSea/opensea-creatures#143]
I wonder what the final reason is to distinguish between `create` and `mint`? 

In both cases a NFT gets minted, right?
But in `create` a creator will be stored, while in `mint` not.

I also could not find any relation to the [official ERC1155-drafts](https://eips.ethereum.org/EIPS/eip-1155) nor any relation to the [Implementation](https://docs.openzeppelin.com/contracts/4.x/api/token/erc1155) of OpenZeppelin.

Is this required for the integration into OpenSea to get listed or what is the reason? For me it seems that OpenSea has its own interpretation of ERC1155 and I'd like to understand why and on which I should rely on: the official one or the example implementation of OpenSea?

_I already asked in the [ERC1155-related project](https://github.com/ProjectOpenSea/opensea-erc1155/issues/57), but it seems to be orphaned that why I'd prefer to ask here (sorry for double posting)._

**Comment by alexanderatallah** [comment]
It's not at all required! it's just a sample way of having
1. a way of creating new token ids (create)
2. a way of minting new copies of an existing token id (mint)

The standard works fine on OpenSea

**Comment by MODEOZO** [comment]
How to mint new token, and create avatar on open sea rarible ? 

What are the fondamental equipment to start a project, 

Should I need to learn a specific code langage for this ?

Please tell me about this, 

Best regards,

Envoyé de mon iPhone
