### ISSUE TITLE
Insufficient funds but my wallet has enough balance.

### ISSUE THREAD

**Issue by shoguniphicus** [ProjectOpenSea/opensea-creatures#150]
Any kind soul to point me in the right direction?
I remember running into this type of error before, but even in the error log, I can see I have enough balance.
Below are part of the logs that I have got when I tried to deploy the contract to Rinkeby network.

Summary
=======
> Total deployments:   2
> Final cost:          0.004312506 ETH

1_initial_migrations.js
=======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0x1cce60f9Abe261C6F682CfE8738fb99568514d31
   * Balance:  28912154977541513 wei
   * Message:  insufficient funds for gas * price + value

**Comment by shoguniphicus** [comment]
Another thing to note is that the only thing I changed is the address and mnemonic, and infura key. Nothing else. so I am quite bummed to see this.

**Comment by gorbunovperm** [comment]
Same issue. The balance is 0.17ETH.
I can see the contract in [etnerscan](https://rinkeby.etherscan.io/address/0xC590D4B9ee3cDcEB07196f380679b2E47e979985), but at the same time, as a result of the command execution, I see an error.

Command:
`DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby`

Result:

```
Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 29970705 (0x1c95111)


2_deploy_contracts.js
=====================

   Deploying 'Creature'
   --------------------
   > transaction hash:    0xd203a47c6681c23a43f5545cd7d0d0f1ac37b144c4472fe55aa7c7658d8a9119
   > Blocks: 2            Seconds: 20
   > contract address:    0xC590D4B9ee3cDcEB07196f380679b2E47e979985
   > block number:        9573382
   > block timestamp:     1635861124
   > account:             0x3Cea5eE28963A7dB9A35E44a05fd787CF588BE79
   > balance:             0.134776275935265918
   > gas used:            2119557 (0x205785)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04239114 ETH


   Deploying 'CreatureFactory'
   ---------------------------


Error:  *** Deployment Failed ***

"CreatureFactory" could not deploy due to insufficient funds
   * Account:  0x3Cea5eE28963A7dB9A35E44a05fd787CF588BE79
   * Balance:  134776275935265918 wei
   * Message:  insufficient funds for gas * price + value
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.

    at /home/opensea-creatures/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at module.exports (/home/opensea-creatures/migrations/2_deploy_contracts.js:39:5)
    at Migration._deploy (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:79:1)
    at Migration._load (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:226:1)
    at Command.run (/home/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.5 (core: 5.2.5)
Node v12.22.7
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nimamoradi** [comment]
@shoguniphicus have you find any fixes, i am having the same issue

**Comment by humanwhoexplores** [comment]
Hello folks, 
I faced this issue once and this was the cause 

In my deploy function  I was using syntax for a different version of truffle-hd-wallet-provider. 

Truffle is under active development .Can you please confirm if you are using the Truffle version as needed here https://github.com/ProjectOpenSea/opensea-creatures/blob/master/package.json#L31

**Comment by humanwhoexplores** [comment]
I faced this issue and then i re-deployed the contract on Rinkeby after 2 hours and this solved the issue. So seems like it was an intermittent issue. 

If this doesn not  solve the issue can you share 'truffle.js' and 'package.json'

**Comment by jimenofonseca** [comment]
@humanwhoexplores same issue here, trying for over 2 days in a row. The funny thing is that the simulation (dry run) passes through but the rest does not. same error.

**Comment by humanwhoexplores** [comment]
@jimenofonseca  Hey can you please share your 'truffle.js' and 'package.json'

**Comment by jimenofonseca** [comment]
Hey I think I solved the issue. I just tuned the gas parameters

for deploying contracts in 2_deploy_contracts.js reduced to 2000000
for gas in rinkbey network in truffle.js reduced to 2000000

It worked! what do you think?

**Comment by humanwhoexplores** [comment]
@jimenofonseca  Hello , I faced this issue again today , let me share an example to explain this 


Summary
=======
> Total deployments:   1
> Final cost:          0.003550094 ETH


Error: err: insufficient funds for gas * price + value: address have 69845043488317125 want 100000000000000000 (supplied gas 5000005)


At this moment :- my wallet had 0.0698 ETH : which is Wei is 69845043488317125

Question  :- if Final_Cost(0.003550094 ETH) < Wallet Balance:
then why do i get the insufficient funds error

The reason is in **truffle.js** and **2_deploy_contracts.js**  
https://github.com/ProjectOpenSea/opensea-creatures/blob/master/truffle.js#L37
https://github.com/ProjectOpenSea/opensea-creatures/blob/master/migrations/2_deploy_contracts.js#L35

the Gas configured is 5000000 . This is the Gas limit (the max gas that can be used)
From the docs :-  the price per unit of the gas is 20 gwei 
https://trufflesuite.com/docs/truffle/reference/configuration.html
5000000 * 20 gwei = 100000000000000000 wei 

Even though the gas required is less than the limit, it  errors out because the eth in  my wallet is less than the gas limit 100000000000000000 wei  .

Hence, when we decrease the gaslimit in above hyperlinked lines the deployment is successful

**Comment by shoguniphicus** [comment]
Thanks @humanwhoexplores, the devil was in the details. It's just not that obvious.
