### ISSUE TITLE
What is the 2nd constructor argument in deployer.deploy?

### ISSUE THREAD

**Issue by villarode** [ProjectOpenSea/opensea-creatures#154]
Guys in the standard OpenSea docs what is the parameter in the constructor?

constructor(address _proxyRegistryAddress)
ERC721Tradable("Villa_Rode_AL_OS721_Rinkeby", "OSC", _proxyRegistryAddress)
{}

I'm just trying to do the second deploy for my own contract Villa_Rode_AL and do not understand what needs to go into the constructor argument in deployer.deploy after the name of my contract:

const Villa_Rode_AL = artifacts.require("Villa_Rode_AL");
module.exports = function (deployer) {
deployer.deploy(Villa_Rode_AL);
};

**Comment by villarode** [comment]
I ended up just writing OpenSea Registry address for rinkeby as the second argument in deployer.deploy:

const Villa_Rode_AL = artifacts.require("Villa_Rode_AL");
module.exports = function (deployer) {
deployer.deploy(Villa_Rode_AL, "0xF57B2c51dED3A29e6891aba85459d600256Cf317");
};

Is it the right thing to do?)

**Comment by alexanderatallah** [comment]
The second argument is the contract's "symbol", which shows up in ERC20 token trackers.

**Comment by villarode** [comment]
Alexander, thank you, I probably was not clear asking my question)

I am meaning the deployer function in scripts/mint.js file. Do I need to explicitly specify OpenSea Registry address for a particular network as the second argument, e.g.:

deployer.deploy(Villa_Rode_AL, "0xF57B2c51dED3A29e6891aba85459d600256Cf317"); - for Rinkeby network?

Once I put that address in everything started to work. Is it because in the contract itself I am using that registry address as the constructor argument constructor(address _proxyRegistryAddress) ?

Is it something specifically needed for whitelisting function? Thanks!)
