### ISSUE TITLE
How do I create and mint tokens with my metadata within the created and verified 721 contract?

### ISSUE THREAD

**Issue by villarode** [ProjectOpenSea/opensea-creatures#156]
Guys hi I seem to be stuck and it is probably some minor thing holding me up here(( The contract ERC721 is succesfully created 0x08B3Ad0020a390F893098EC83BC64c541a276c11 and verified.

I'm using the template for 721 contract from OpenSea doc and a sample scripts/mint.js file from here:

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import "./ERC721Tradable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
/**
@title Villa_Rode_AL_OS721_Rinkeby
Creature - a contract for my non-fungible creatures.
*/

contract Villa_Rode_AL is ERC721Tradable {
constructor(address _proxyRegistryAddress)
ERC721Tradable("Villa_Rode_AL_OS721_Rinkeby", "OSC", _proxyRegistryAddress)
{}

function baseTokenURI() override public pure returns (string memory) {
return "https:/gateway.pinata.cloud/ipfs/QmYqKdKrjPfD7KBqq7pkpaLCJdc4hzgcQWMHime5qcSgaE/";
}

/////function contractURI() public pure returns (string memory) {
/////return "https://creatures-api.opensea.io/contract/opensea-creatures";
/////}
}

I am uploading a photo to IPFS thru Pinata, Then I create nft-metadata.json file with photo's hash and also upload it to Pinata. Then I include this file's hash into return line of the contract (as seen above). Problem is I can't access the photo directly thru pinata, is it because gateway is only on paid subscriptions to pinata? (I am still on a free one)

I am seemingly getting all bits and pieces correctly:

3. baseTokenURI
https://gateway.pinata.cloud/ipfs/QmQ4btGqRKfLwfJgAuh7k3cAqRDQZj1WTV1L8f9EhdunHQ/ string

17. tokenURI
_tokenId (uint256)
1
 string
[ tokenURI(uint256) method Response ]
    string :  https://gateway.pinata.cloud/ipfs/QmYqKdKrjPfD7KBqq7pkpaLCJdc4hzgcQWMHime5qcSgaE/1

with .../1 link at the end etc..... I'm assuming that number is for my would-be token.

BUT there are no tokens, no metedata, and when I run that .../1 link I am getting an error. And when I try to run
https://testnets.opensea.io/assets/0x08B3Ad0020a390F893098EC83BC64c541a276c11 with my contract address I'm getting message 404 Page is lost even though I can see my contract on rinkeby.etherscan.io perfectly well....

What might be the problem? Is it because of Pinata not loading my metedata for some reason? Cheers in advance

**Comment by BlikDik** [comment]
As I understand it is the correct standard for IPFS ipfs://<hash>. 
For example, ipfs://QmTy8w65yBXgyfG2ZBg5TrfB2hPjrDQH3RCQFJGkARStJb.
https://docs.opensea.io/docs/metadata-standards

**Comment by alexanderatallah** [comment]
You need a token ID at the end of your item url: https://testnets.opensea.io/assets/0x08B3Ad0020a390F893098EC83BC64c541a276c11/1

See docs.opensea.io/docs for tips on validating your metadata. You can use the /validate endpoint: https://testnets-api.opensea.io/asset/0x08B3Ad0020a390F893098EC83BC64c541a276c11/1/validate

**Comment by villarode** [comment]
Thank you mate, much appreciated!)

**Comment by villarode** [comment]
Many thanks for your reply!) Much appreciated!)

**Comment by gelinger777** [comment]
@villarode  have you figured it out how to achieve it with Pinata?
