### ISSUE TITLE
Issue with "wyvern-js/src/wyvern-ethereum/test/aux.js" on Windows 10

### ISSUE THREAD

**Issue by FredM10** [ProjectOpenSea/opensea-creatures#16]
Getting the following error when trying to "npm install" on Windows 10:

```
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b v3.0.2 git://github.com/ProjectOpenSea/wyvern-js.git C:\Users\frede\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-dae6f3a7 --config core.longpaths=true
npm ERR! warning: templates not found C:\Users\frede\AppData\Local\Temp\pacote-git-template-tmp\git-clone-3e664c2a
npm ERR! Note: checking out '1cbed592e7440f097817bcb1a3c789d2b3adc081'.
npm ERR!
npm ERR! You are in 'detached HEAD' state. You can look around, make experimental
npm ERR! changes and commit them, and you can discard any commits you make in this
npm ERR! state without impacting any branches by performing another checkout.
npm ERR!
npm ERR! If you want to create a new branch to retain commits you create, you may
npm ERR! do so (now or later) by using -b with the checkout command again. Example:
npm ERR!
npm ERR!   git checkout -b <new-branch-name>
npm ERR!
npm ERR! error: unable to create file src/wyvern-ethereum/test/aux.js: No such file or directory
npm ERR! fatal: unable to checkout working tree
npm ERR! warning: Clone succeeded, but checkout failed.
npm ERR! You can inspect what was checked out with 'git status'
npm ERR! and retry the checkout with 'git checkout -f HEAD'
npm ERR!
npm ERR!
```

Maybe related to the fact "aux" is a reserved filename in Windows?
https://github.com/gajus/react-aux/issues/10

Thanks for your support!

**Comment by joshuawu** [comment]
Hey @FredM10, thanks for reporting this issue!
Could you try changing https://github.com/ProjectOpenSea/opensea-creatures/blob/15a27aab9d7ffb9860faab27a8127f8eae9eb297/package.json#L21 to this?
```
"opensea-js": "github:joshuawu/opensea-js",
```
Let me know if that fixes it.

**Comment by FredM10** [comment]
Now I get:

`npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE submodule update -q --init --recursive
npm ERR! warning: templates not found C:\Users\frede\AppData\Local\Temp\pacote-git-template-tmp\git-clone-00684b78
npm ERR! warning: templates not found C:\Users\frede\AppData\Local\Temp\pacote-git-template-tmp\git-clone-00684b78
npm ERR! fatal: No url found for submodule path 'examples/opensea-creatures/metadata-api/src/microraiden' in .gitmodules
npm ERR! Failed to recurse into submodule path 'examples/opensea-creatures'
npm ERR!
`

**Comment by joshuawu** [comment]
Could you try deleting your `npm_modules/` folder and `package-lock.json` file and run `npm install` again?

**Comment by FredM10** [comment]
Do you mean deleting the `node_modules/` folder and `package-lock.json` file , in the local directory?

After doing this and running `npm install` again, still get the same error:

`npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE submodule update -q --init --recursive
npm ERR! warning: templates not found C:\Users\frede\AppData\Local\Temp\pacote-git-template-tmp\git-clone-79bdb693
npm ERR! warning: templates not found C:\Users\frede\AppData\Local\Temp\pacote-git-template-tmp\git-clone-79bdb693
npm ERR! fatal: No url found for submodule path 'examples/opensea-creatures/metadata-api/src/microraiden' in .gitmodules
npm ERR! Failed to recurse into submodule path 'examples/opensea-creatures'
npm ERR!
`

**Comment by joshuawu** [comment]
@FredM10 DM'd me on Discord and let me know that my fix worked, so this issue can be closed.
