### ISSUE TITLE
Transfer NFT

### ISSUE THREAD

**Issue by curcaandrei** [ProjectOpenSea/opensea-creatures#209]
Hello,
I'm kinda new to OpeanSea Api and I have to do an app for my bachelors degree which rewards users with NFTs. Is there a simple way to transfer a NFT? I want to integrate this feature into my app.

**Comment by jschiarizzi** [comment]
I suggest you check out Open Zeppelin's ERC721 documentation. You can make an NFT as a 721, and call `transfer` function any time. Good luck. https://docs.openzeppelin.com/contracts/4.x/erc721
