### ISSUE TITLE
Error: make failed with exit code 2

### ISSUE THREAD

**Issue by ShabanShaame** [ProjectOpenSea/opensea-creatures#24]
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/Users/shabanshaame/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Darwin 18.7.0
> gyp ERR! command "/Users/me/.nvm/versions/node/v8.11.4/bin/node" "/Users/me/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/me/htdocs/path/node_modules/ganache-core/node_modules/sha3
> gyp ERR! node -v v8.11.4
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules/ganache-core/node_modules/scrypt):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sha3@1.2.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

On OSX
node -v v8.11.4

It's the same issue as here
https://github.com/ProjectOpenSea/opensea-creatures/issues/8

Thanks for you help !

**Comment by alexanderatallah** [comment]
Switched to node version 12 and yarn - should work better now!
