### ISSUE TITLE
Compiler Error for Proxy Accounts.

### ISSUE THREAD

**Issue by woodydeck** [ProjectOpenSea/opensea-creatures#45]
There is no explanation how to set this up in the docs. I get the following error when compiling. It would be nice to see how you setup the constructor and metadata. I'm using Remix.

`browser/erc1155.sol:216:12: TypeError: Member "isApprovedForAll" not found or not visible after argument-dependent lookup in type(contract ERC1155). return ERC1155.isApprovedForAll(_owner, _operator); ^----------------------^
`

```
  function isApprovedForAll(
    address _owner,
    address _operator
  ) public view returns (bool isOperator) {
    // Whitelist OpenSea proxy contract for easy trading.
    ProxyRegistry proxyRegistry = ProxyRegistry(proxyRegistryAddress);
    if (address(proxyRegistry.proxies(_owner)) == _operator) {
      return true;
    }

    return ERC1155.isApprovedForAll(_owner, _operator);
  }
```

**Comment by alexanderatallah** [comment]
If you're using remix, you need to include the entire ERC1155 contract code exactly as we imported in this repo. Thus, it must come from the multi-token-standard github repo and be at least the version specified in package.json. Likely, one of those two things is not true

**Comment by woodydeck** [comment]
I got it working (as in everything importing to OpenSea too) with stock Open Zeppelin ERC1155. When I'm done I will make a blog about working with ERC1155. Truffle is very fickle and makes testing/setup take longer (imo). The advantage is working with a team. It's all good in Remix now. 

Metadata requires this: https://forum.openzeppelin.com/t/how-to-erc-1155-id-substitution-for-token-uri/3312 for anyone looking. I advise strongly against having an API as a point of failure and centralization for metadata for most projects.

**Comment by villarode** [comment]
Guys in the standard OpenSea docs what is the parameter in the constructor?

constructor(address _proxyRegistryAddress)
ERC721Tradable("Villa_Rode_AL_OS721_Rinkeby", "OSC", _proxyRegistryAddress)
{}

I'm just trying to do the second deploy for my own contract Villa_Rode_AL and do not understand what needs to go into the constructor argument in deployer.deploy

const Villa_Rode_AL = artifacts.require("Villa_Rode_AL");
module.exports = function (deployer) {
  deployer.deploy(Villa_Rode_AL);
};
