### ISSUE TITLE
'npm install' always fails - old/broken dependencies?

### ISSUE THREAD

**Issue by ratio91** [ProjectOpenSea/opensea-creatures#5]
Hi, 
I tried to run ´npm install´ on several systems (windows, linux, var. fresh docker containers, etc), but always got lots of errors. I use nvm and node 8.11.2 as suggested, but to no avail.
Could you please check the package dependencies and maybe take the effort to update everything to solidity 0.5? thanks!

**Comment by dfinzer** [comment]
Hey! Sorry bout that. I'm on a mac and I can't seem to reproduce. What errors are you getting?

**Comment by alexanderatallah** [comment]
@pl4ym0re @ratio91 see https://github.com/nodejs/node-gyp/issues/569

Does that fix it for you?

**Comment by pl4ym0re** [comment]
Already tried 😉 but I still get errors. Didn't install the full Xcode just the command line tools but as they say : 
> Command Line Tools works fine, you do not need the full Xcode.

**Comment by pl4ym0re** [comment]
I finally make it work! So what I did:

- Install Command Line Tools (if you haven't already)
`xcode-select --install`
- Enable command line tools
`sudo xcode-select --switch /Library/Developer/CommandLineTools` 
- Update node-gyp
`sudo npm explore npm -g -- npm install node-gyp@latest`

**Comment by alexanderatallah** [comment]
Awesome! updated the docs

**Comment by pedroamd** [comment]
This works for me

npm install -g n
n 8.8.1

sudo npm explore npm -g -- npm install node-gyp@latest
