### ISSUE TITLE
Error: Deployment to Rinkeby is not working

### ISSUE THREAD

**Issue by pkrasam** [ProjectOpenSea/opensea-creatures#6]
I am getting this error when deploying to Rinkeby network

71 verbose stack Error: Command failed: /usr/local/bin/git submodule update -q --init --recursive
71 verbose stack error: could not lock config file .git/config: Permission denied
71 verbose stack error: could not lock config file .git/config: Permission denied
71 verbose stack fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
71 verbose stack
71 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
71 verbose stack     at ChildProcess.emit (events.js:189:13)
71 verbose stack     at maybeClose (internal/child_process.js:970:16)
71 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
72 verbose cwd /Users/pk/Documents/code/opensea-creatures
73 verbose Darwin 18.2.0
74 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "truffle-hdwallet-provider@web3-one"
75 verbose node v10.15.1
76 verbose npm  v6.4.1
77 error code 128
78 error Command failed: /usr/local/bin/git submodule update -q --init --recursive
78 error error: could not lock config file .git/config: Permission denied
78 error error: could not lock config file .git/config: Permission denied
78 error fatal: Failed to register url for submodule path 'src/wyvern-ethereum'
79 verbose exit [ 1, true ]

**Comment by alexanderatallah** [comment]
This should be fixed now! let us know if not.
