### ISSUE TITLE
ERC1155Tradable  test failure

### ISSUE THREAD

**Issue by akutruff** [ProjectOpenSea/opensea-creatures#61]
1) Contract: ERC1155Tradable - ERC 1155
       #setCreator()
         should allow the token creator to set creator to another address:

      AssertionError: expected '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1' to equal '0x22d491Bde2303f2f43325b2108D26f1eAbA1e32b'
      + expected - actual

      -0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
      +0x22d491Bde2303f2f43325b2108D26f1eAbA1e32b
      
      at Context.<anonymous> (test/ERC1155Tradable.js:226:17)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by TheMaxKim** [comment]
Thanks for the report, I believe this is due to not having an `await` statement in the test for the transaction to be completed to update the creator. Should have this fixed in this PR shortly: https://github.com/ProjectOpenSea/opensea-creatures/pull/62
