### ISSUE TITLE
Error: npm install

### ISSUE THREAD

**Issue by pkrasam** [ProjectOpenSea/opensea-creatures#7]
Getting this error...

npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout HEAD
npm ERR! git-lfs filter-process: git-lfs: command not found
npm ERR! fatal: the remote end hung up unexpectedly
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pk/.npm/_logs/2019-03-06T07_19_31_282Z-debug.log

**Comment by pfaraee** [comment]
Getting similar error after `npm install`:

`
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout HEAD
npm ERR! git-lfs smudge 'src/wyvern-ethereum/utxo-merkle-proof/package.json': git-lfs: command not found
npm ERR! error: external filter 'git-lfs smudge %f' failed 127
npm ERR! error: external filter 'git-lfs smudge %f' failed
npm ERR! fatal: src/wyvern-ethereum/utxo-merkle-proof/package.json: smudge filter lfs failed
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philippfaraee/.npm/_logs/2019-04-07T15_36_00_891Z-debug.log
`

tried with nvm on and off, and pasting the snippet that was provided for Mac users.

**Comment by dfinzer** [comment]
This should be fixed now!
