### ISSUE TITLE
How can I deploy the CreatureFactory using web3js, not with truffle?

### ISSUE THREAD

**Issue by djpysu** [ProjectOpenSea/opensea-creatures#77]
So, if you want to have dynamic owners of the contract, you have to build (solc) and deploy the contract using web3js.

Is it possible to deploy the CreatureFactory like this? How?

Or, is there any other way to mint the token to a different address than the owner of the contract?

**Comment by jackey** [comment]
So do u get a solution here ? i meet a same problem here.

**Comment by djpysu** [comment]
Yes, you can compile with solcjs and then deploy with web3js
