### ISSUE TITLE
ERC721Full.sol  where are you?

### ISSUE THREAD

**Issue by Baron-de-Andre** [ProjectOpenSea/opensea-creatures#78]
openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol ???? where is this file

**Comment by TheMaxKim** [comment]
This is in the OpenZeppelin NPM release that we reference within the package.json, and should automatically be pulled down for you: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.1.3/contracts/token/ERC721/ERC721Full.sol
