### ISSUE TITLE
Error: make failed with exit code 2

### ISSUE THREAD

**Issue by pkrasam** [ProjectOpenSea/opensea-creatures#8]
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pk/Documents/code/opensea-creatures/node_modules/sha3
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pk/.npm/_logs/2019-03-06T07_47_54_424Z-debug.log

**Comment by blockinator** [comment]
Make sure you have all dependancies installed:

```
sudo apt-get install libusb-1.0-0-dev

sudo apt-get install libudev-dev

npm install -g node-gyp@latest
```

Then remove node_modules:

```
rm -r node_modules
```
Then run ```npm install``` again.

**Comment by alexanderatallah** [comment]
Also make sure you're using the right node version before running `npm install`. see https://github.com/ProjectOpenSea/opensea-creatures/blob/master/README.md#node-version

**Comment by ShabanShaame** [comment]
Hello !
I'm running into the same issue

On OSX
 node -v v8.11.4

**Comment by isaacschaal** [comment]
I found that uninstalling and reinstalling xcode solved an exit code 1 problem for me, could be worth a try. (from https://github.com/schnerd/d3-scale-cluster/issues/7)
