### ISSUE TITLE
Gas free minting on CreatureFactory doesn't work

### ISSUE THREAD

**Issue by djpysu** [ProjectOpenSea/opensea-creatures#80]
Everything works kind of ok. Compiling and deploying the contracts are also managed quite ok.

Then, using mint.js I can mint one Creature to my own address. All good. But when I do mint again, it will cost me gas, even if the proxy contract from OpenSea is there. What are we missing here?

Please help :octocat:

**Comment by TheMaxKim** [comment]
I think "gas free minting" is a bit of a misnomer in this case and isn't available through the CreatureFactory contract. The CreatureFactory contract lets you create sell orders for the Creature NFT / token on OpenSea without having spent gas on minting those, by supporting minting through the [transfer method](https://github.com/ProjectOpenSea/opensea-creatures/blob/master/contracts/CreatureFactory.sol#L139). But gas will eventually have to be spent to mint the NFTs on the blockchain.

One can create NFTs that can be managed on OpenSea without spending gas [here](https://opensea.io/collections), but I believe those aren't actually "minted" onto the blockchain either until traded.
