### ISSUE TITLE
How to get Address of Deployed Contract?

### ISSUE THREAD

**Issue by AdamZWinter** [ProjectOpenSea/opensea-creatures#85]
How do I get the address of the deployed contract if I just happened to have not grabbed it from the output when I deployed the contract?

I got pulled away to do something else right at that point, then lost that screen before I was able to get back to it.  0

Thank you.

**Comment by alexanderatallah** [comment]
I believe you can do `truffle console` and then `await OpenSeaCreatures.deployed()` to get the contract, and then read its `.address`
