### ISSUE TITLE
Stuck on `Compiling your contracts...`

### ISSUE THREAD

**Issue by baxterjfinch** [ProjectOpenSea/opensea-creatures#9]
There isn't any output nor are there any errors. When I run `truffle deploy --network rinkeby` it hangs on `Compiling your contracts`.

Anyone experience this? Followed the readme verbatim. 

Running Ubuntu 18.04

**Comment by blockinator** [comment]
### Make sure you have all dependancies installed:

```
sudo apt update
```
```
sudo apt-get install libusb-1.0-0-dev
```
```
sudo apt-get install libudev-dev
```
```
npm install -g node-gyp@latest
```
```
sudo apt install nodejs
```
```
sudo apt install npm
```

### Install ```nvm```:

```
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh -o install_nvm.sh
```
```
bash install_nvm.sh
```

### Reboot to use nvm:

```
sudo reboot
```

### Enter opensea-creatures directory and run npm install:

```
cd opensea-creatures && npm install
```

**Comment by alexanderatallah** [comment]
@blockinator thanks for that! @hemlokc did that end up helping?
